unzip -q jdk1.9.0.jdk/Contents/Home/jmods/java.activation.jmod -d build/mods/java.activation.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/java.annotations.common.jmod -d build/mods/java.annotations.common.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/java.base.jmod -d build/mods/java.base.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/java.compact1.jmod -d build/mods/java.compact1.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/java.compact2.jmod -d build/mods/java.compact2.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/java.compact3.jmod -d build/mods/java.compact3.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/java.compiler.jmod -d build/mods/java.compiler.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/java.corba.jmod -d build/mods/java.corba.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/java.datatransfer.jmod -d build/mods/java.datatransfer.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/java.desktop.jmod -d build/mods/java.desktop.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/java.instrument.jmod -d build/mods/java.instrument.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/java.logging.jmod -d build/mods/java.logging.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/java.management.jmod -d build/mods/java.management.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/java.naming.jmod -d build/mods/java.naming.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/java.prefs.jmod -d build/mods/java.prefs.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/java.rmi.jmod -d build/mods/java.rmi.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/java.scripting.jmod -d build/mods/java.scripting.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/java.se.jmod -d build/mods/java.se.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/java.security.jgss.jmod -d build/mods/java.security.jgss.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/java.security.sasl.jmod -d build/mods/java.security.sasl.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/java.smartcardio.jmod -d build/mods/java.smartcardio.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/java.sql.jmod -d build/mods/java.sql.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/java.sql.rowset.jmod -d build/mods/java.sql.rowset.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/java.transaction.jmod -d build/mods/java.transaction.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/java.xml.bind.jmod -d build/mods/java.xml.bind.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/java.xml.crypto.jmod -d build/mods/java.xml.crypto.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/java.xml.jmod -d build/mods/java.xml.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/java.xml.ws.jmod -d build/mods/java.xml.ws.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/javafx.base.jmod -d build/mods/javafx.base.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/javafx.controls.jmod -d build/mods/javafx.controls.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/javafx.deploy.jmod -d build/mods/javafx.deploy.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/javafx.fxml.jmod -d build/mods/javafx.fxml.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/javafx.graphics.jmod -d build/mods/javafx.graphics.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/javafx.media.jmod -d build/mods/javafx.media.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/javafx.swing.jmod -d build/mods/javafx.swing.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/javafx.web.jmod -d build/mods/javafx.web.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.accessibility.jmod -d build/mods/jdk.accessibility.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.attach.jmod -d build/mods/jdk.attach.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.charsets.jmod -d build/mods/jdk.charsets.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.compiler.jmod -d build/mods/jdk.compiler.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.crypto.ec.jmod -d build/mods/jdk.crypto.ec.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.crypto.pkcs11.jmod -d build/mods/jdk.crypto.pkcs11.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.deploy.jmod -d build/mods/jdk.deploy.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.deploy.osx.jmod -d build/mods/jdk.deploy.osx.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.hotspot.agent.jmod -d build/mods/jdk.hotspot.agent.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.httpserver.jmod -d build/mods/jdk.httpserver.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.internal.le.jmod -d build/mods/jdk.internal.le.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.internal.opt.jmod -d build/mods/jdk.internal.opt.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.jartool.jmod -d build/mods/jdk.jartool.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.javadoc.jmod -d build/mods/jdk.javadoc.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.javaws.jmod -d build/mods/jdk.javaws.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.jcmd.jmod -d build/mods/jdk.jcmd.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.jconsole.jmod -d build/mods/jdk.jconsole.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.jdeps.jmod -d build/mods/jdk.jdeps.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.jdi.jmod -d build/mods/jdk.jdi.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.jdwp.agent.jmod -d build/mods/jdk.jdwp.agent.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.jfr.jmod -d build/mods/jdk.jfr.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.jlink.jmod -d build/mods/jdk.jlink.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.jvmstat.jmod -d build/mods/jdk.jvmstat.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.localedata.jmod -d build/mods/jdk.localedata.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.management.cmm.jmod -d build/mods/jdk.management.cmm.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.management.jmod -d build/mods/jdk.management.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.management.resource.jmod -d build/mods/jdk.management.resource.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.naming.dns.jmod -d build/mods/jdk.naming.dns.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.naming.rmi.jmod -d build/mods/jdk.naming.rmi.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.pack200.jmod -d build/mods/jdk.pack200.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.plugin.dom.jmod -d build/mods/jdk.plugin.dom.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.plugin.jmod -d build/mods/jdk.plugin.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.policytool.jmod -d build/mods/jdk.policytool.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.rmic.jmod -d build/mods/jdk.rmic.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.scripting.nashorn.jmod -d build/mods/jdk.scripting.nashorn.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.scripting.nashorn.shell.jmod -d build/mods/jdk.scripting.nashorn.shell.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.sctp.jmod -d build/mods/jdk.sctp.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.security.auth.jmod -d build/mods/jdk.security.auth.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.security.jgss.jmod -d build/mods/jdk.security.jgss.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.snmp.jmod -d build/mods/jdk.snmp.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.xml.bind.jmod -d build/mods/jdk.xml.bind.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.xml.dom.jmod -d build/mods/jdk.xml.dom.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.xml.ws.jmod -d build/mods/jdk.xml.ws.jmod
unzip -q jdk1.9.0.jdk/Contents/Home/jmods/jdk.zipfs.jmod -d build/mods/jdk.zipfs.jmod

